# Generated by Django 4.0.5 on 2022-06-06 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courses_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
        migrations.RemoveField(
            model_name='users',
            name='courses_library',
        ),
        migrations.AddField(
            model_name='courses',
            name='quiz',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
