# Generated by Django 4.0.5 on 2022-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_courses_users_users_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='courses',
            field=models.ManyToManyField(blank=True, to='api.courses'),
        ),
    ]
